version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - custom_network

  backend:
    build:
      context: ./
      dockerfile: ./cmd/portfolio/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./cmd/portfolio:/app
      - ./icons:/app/icons
      - ./media:/app/media
    networks:
      custom_network:
        aliases:
          - backend
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - portfolio_client_dist_volume:/usr/share/nginx/html
      - ./icons:/app/icons
      - ./media:/app/media
    ports:
      - "80:80"
    networks:
      custom_network:
        aliases:
          - nginx
    depends_on:
      - backend

networks:
  custom_network:
    driver: bridge

volumes:
  portfolio_client_dist_volume:
